name: "Configurar Credenciais"

on:
  workflow_call:  # Permite que este workflow seja chamado por outros workflows

jobs:
  configurar-credenciais:
    name: "Configurar Credenciais da AWS"
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: pip install awscli
        
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Ajuste para sua região