name: "Configurar Credenciais"

on:
  workflow_call:  # Permite ser chamado por outros workflows

jobs:
  configurar-credenciais:
    name: "Configurar Credenciais da AWS"
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: pip install awscli

      - name: Checkout código
        uses: actions/checkout@v4

      - name: Debug - Verificar se AWS_ACCESS_KEY_ID existe
        run: |
          if [[ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]]; then
            echo "❌ ERRO: AWS_ACCESS_KEY_ID não está definido nos Secrets do GitHub."
            exit 1
          else
            echo "✅ AWS_ACCESS_KEY_ID está configurado corretamente."
          fi

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2  # Atualize para v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Ajuste para sua região

      - name: Validar credenciais AWS
        run: aws sts get-caller-identity