name: "Terraform Approval"

on:
  workflow_call:
    inputs:
      approve:
        description: "Aprovação para aplicar mudanças no Terraform (yes/no)"
        required: true
        type: string

jobs:
  approval:
    name: "Aprovação Manual"
    runs-on: ubuntu-latest

    outputs:
      approve: ${{ steps.approval_step.outputs.approve }}

    steps:
      - name: Aguardando Aprovação
        run: echo "Aguardando aprovação manual no GitHub Actions..."

      - name: Approval step
        id: approval_step
        run: echo "::set-output name=approve::yes"

      - name: Verificar Decisão
        id: check_approval
        run: |
          if [[ "${{ inputs.approve }}" == "yes" ]]; then
            echo "Aprovação concedida. Continuando com o Terraform Apply."
            echo "::set-output name=approve::yes"
            gh workflow run terraform-apply.yml --ref ${{ github.ref }} --inputs approve=yes
          else
            echo "Aprovação negada. O processo será interrompido."
            echo "::set-output name=approve::no"
            exit 1
