name: "Terraform Approval"

on:
  workflow_call:
    secrets:
      PAT_GITHUB:
        required: true
    inputs:
      approve:
        description: "Aprovação para aplicar mudanças no Terraform (yes/no)"
        required: true
        type: string

jobs:
  approval:
    name: "Aprovação Manual"
    runs-on: ubuntu-latest
    env:
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}  # Use a personal access token with repo permissions

    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ env.PAT_GITHUB }}
          approvers: alissong
          minimum-approvals: 1
          issue-title: "Approve Terraform Apply"
          issue-body: "Please approve or deny the deployment of the Terraform plan."
          exclude-workflow-initiator-as-approver: false
