name: "Terraform Approval"

on:
  workflow_call:
    inputs:
      approve:
        description: "Aprovação para aplicar mudanças no Terraform (yes/no)"
        required: true
        type: string

jobs:
  approval:
    name: "Aprovação Manual"
    runs-on: ubuntu-latest

    steps:
      - name: Aguardando Aprovação
        run: echo "Aguardando aprovação manual no GitHub Actions..."

      - name: Verificar Decisão
        run: |
          if [[ "${{ inputs.approve }}" == "yes" ]]; then
            echo "Aprovação concedida. Continuando com o Terraform Apply."
          else
            echo "Aprovação negada. O processo será interrompido."
            exit 1
          fi
