name: "Terraform Apply"

on:
  workflow_call:  # Permite que este workflow seja chamado por outros workflows
    inputs:
      approve:
        description: "Aprovação para aplicar mudanças no Terraform (yes/no)"
        required: true
        type: string

jobs:
  terraform-apply:
    name: "Executar Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar aprovação para Apply
        if: ${{ inputs.approve }} == 'yes'
        working-directory: terraform
        run: |
          echo "🚀 Terraform Plan gerado com sucesso!"
          echo "✅ Aprovação recebida. Continuando com Terraform Apply..."
          terragrunt apply -auto-approve

      - name: Cancelar Apply se não aprovado
        if: ${{ inputs.approve }} == 'no'
        run: |
          echo "❌ Deploy cancelado pelo usuário."
          exit 1