name: "Aprovação Terraform"

on:
  workflow_call:
    inputs:
      approve:
        description: "Aprovação para continuar com o Terraform Apply (yes/no)"
        required: true
        type: string

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir Mensagem de Aprovação
        run: echo "Aguardando aprovação manual no GitHub Actions..."

      - name: Decisão de Aprovação
        run: |
          if [[ "${{ inputs.approve }}" == "yes" ]]; then
            echo "Aprovação concedida. Continuando com o Terraform Apply."
          else
            echo "Aprovação negada. O processo será interrompido."
            exit 1
          fi
